# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/i9103/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/i9103/proprietary/bin/nvcpud:system/bin/nvcpud \
    vendor/samsung/i9103/proprietary/bin/cbd:system/bin/cbd \
    vendor/samsung/i9103/proprietary/etc/firmware/nvmm_wavdec.axf:system/etc/firmware/nvmm_wavdec.axf \
    vendor/samsung/i9103/proprietary/etc/firmware/nvmm_mpeg4dec.axf:system/etc/firmware/nvmm_mpeg4dec.axf \
    vendor/samsung/i9103/proprietary/etc/firmware/nvmm_vc1dec.axf:system/etc/firmware/nvmm_vc1dec.axf \
    vendor/samsung/i9103/proprietary/etc/firmware/nvmm_jpegenc.axf:system/etc/firmware/nvmm_jpegenc.axf \
    vendor/samsung/i9103/proprietary/etc/firmware/bcm4330.hcd:system/etc/firmware/bcm4330.hcd \
    vendor/samsung/i9103/proprietary/etc/firmware/nvmm_service.axf:system/etc/firmware/nvmm_service.axf \
    vendor/samsung/i9103/proprietary/etc/firmware/nvmm_mp3dec.axf:system/etc/firmware/nvmm_mp3dec.axf \
    vendor/samsung/i9103/proprietary/etc/firmware/nvmm_wmaprodec.axf:system/etc/firmware/nvmm_wmaprodec.axf \
    vendor/samsung/i9103/proprietary/etc/firmware/nvmm_wmadec.axf:system/etc/firmware/nvmm_wmadec.axf \
    vendor/samsung/i9103/proprietary/etc/firmware/nvmm_h264dec.axf:system/etc/firmware/nvmm_h264dec.axf \
    vendor/samsung/i9103/proprietary/etc/firmware/nvmm_manager.axf:system/etc/firmware/nvmm_manager.axf \
    vendor/samsung/i9103/proprietary/etc/firmware/nvmm_vc1dec_2x.axf:system/etc/firmware/nvmm_vc1dec_2x.axf \
    vendor/samsung/i9103/proprietary/etc/firmware/nvmm_adtsdec.axf:system/etc/firmware/nvmm_adtsdec.axf \
    vendor/samsung/i9103/proprietary/etc/firmware/nvrm_avp.bin:system/etc/firmware/nvrm_avp.bin \
    vendor/samsung/i9103/proprietary/etc/firmware/nvmm_jpegdec.axf:system/etc/firmware/nvmm_jpegdec.axf \
    vendor/samsung/i9103/proprietary/etc/firmware/nvmm_aacdec.axf:system/etc/firmware/nvmm_aacdec.axf \
    vendor/samsung/i9103/proprietary/etc/wifi/bcm4330_p2p.bin:system/etc/wifi/bcm4330_p2p.bin \
    vendor/samsung/i9103/proprietary/etc/wifi/bcm4330_sta.bin:system/etc/wifi/bcm4330_sta.bin \
    vendor/samsung/i9103/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/i9103/proprietary/etc/wifi/nvram_net.txt_murata:system/etc/wifi/nvram_net.txt_murata \
    vendor/samsung/i9103/proprietary/etc/wifi/bcm4330_apsta.bin:system/etc/wifi/bcm4330_apsta.bin \
    vendor/samsung/i9103/proprietary/usr/keylayout/sec_touchscreen.kl:system/usr/keylayout/sec_touchscreen.kl \
    vendor/samsung/i9103/proprietary/usr/keylayout/Vendor_046d_Product_c21f.kl:system/usr/keylayout/Vendor_046d_Product_c21f.kl \
    vendor/samsung/i9103/proprietary/usr/keylayout/sec_key.kl:system/usr/keylayout/sec_key.kl \
    vendor/samsung/i9103/proprietary/usr/keylayout/Vendor_057e_Product_0306.kl:system/usr/keylayout/Vendor_057e_Product_0306.kl \
    vendor/samsung/i9103/proprietary/usr/keylayout/Vendor_046d_Product_c21d.kl:system/usr/keylayout/Vendor_046d_Product_c21d.kl \
    vendor/samsung/i9103/proprietary/usr/keylayout/Vendor_2378_Product_100a.kl:system/usr/keylayout/Vendor_2378_Product_100a.kl \
    vendor/samsung/i9103/proprietary/usr/keylayout/Vendor_04e8_Product_7021.kl:system/usr/keylayout/Vendor_04e8_Product_7021.kl \
    vendor/samsung/i9103/proprietary/usr/keylayout/Bluetooth_00_06_66_42.kl:system/usr/keylayout/Bluetooth_00_06_66_42.kl \
    vendor/samsung/i9103/proprietary/usr/keylayout/sec_jack.kl:system/usr/keylayout/sec_jack.kl \
    vendor/samsung/i9103/proprietary/usr/keylayout/Vendor_044f_Product_d007.kl:system/usr/keylayout/Vendor_044f_Product_d007.kl \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvwinsys.so:system/vendor/lib/libnvwinsys.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvodm_hdmi.so:system/vendor/lib/libnvodm_hdmi.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvrm.so:system/vendor/lib/libnvrm.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvmm_audio.so:system/vendor/lib/libnvmm_audio.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvrm_graphics.so:system/vendor/lib/libnvrm_graphics.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvmm.so:system/vendor/lib/libnvmm.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvddk_2d_v2.so:system/vendor/lib/libnvddk_2d_v2.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvmm_utils.so:system/vendor/lib/libnvmm_utils.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvsm.so:system/vendor/lib/libnvsm.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvparser.so:system/vendor/lib/libnvparser.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvmm_vc1_video.so:system/vendor/lib/libnvmm_vc1_video.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvmm_parser.so:system/vendor/lib/libnvmm_parser.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libcgdrv.so:system/vendor/lib/libcgdrv.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvavp.so:system/vendor/lib/libnvavp.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvtestio.so:system/vendor/lib/libnvtestio.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvomxilclient.so:system/vendor/lib/libnvomxilclient.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvasfparserhal.so:system/vendor/lib/libnvasfparserhal.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libmlplatform.so:system/vendor/lib/libmlplatform.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvcpud.so:system/vendor/lib/libnvcpud.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvmm_camera.so:system/vendor/lib/libnvmm_camera.so \
    vendor/samsung/i9103/proprietary/vendor/lib/hw/camera.vendor.tegra.so:system/vendor/lib/hw/camera.vendor.tegra.so \
    vendor/samsung/i9103/proprietary/vendor/lib/hw/gps.tegra.so:system/vendor/lib/hw/gps.tegra.so \
    vendor/samsung/i9103/proprietary/vendor/lib/hw/gralloc.tegra.so:system/vendor/lib/hw/gralloc.tegra.so \
    vendor/samsung/i9103/proprietary/vendor/lib/hw/sensors.n1.so:system/vendor/lib/hw/sensors.n1.so \
    vendor/samsung/i9103/proprietary/vendor/lib/hw/hwcomposer.tegra.so:system/vendor/lib/hw/hwcomposer.tegra.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvodm_misc.so:system/vendor/lib/libnvodm_misc.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libsecril-client.so:system/vendor/lib/libsecril-client.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvmm_msaudio.so:system/vendor/lib/libnvmm_msaudio.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvddk_2d.so:system/vendor/lib/libnvddk_2d.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvodm_query.so:system/vendor/lib/libnvodm_query.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libakm.so:system/vendor/lib/libakm.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvodm_imager.so:system/vendor/lib/libnvodm_imager.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvmm_writer.so:system/vendor/lib/libnvmm_writer.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libmllite.so:system/vendor/lib/libmllite.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libstagefrighthw.so:system/vendor/lib/libstagefrighthw.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvtestresults.so:system/vendor/lib/libnvtestresults.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvodm_dtvtuner.so:system/vendor/lib/libnvodm_dtvtuner.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvwsi.so:system/vendor/lib/libnvwsi.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvaviparserhal.so:system/vendor/lib/libnvaviparserhal.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvmmlite.so:system/vendor/lib/libnvmmlite.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvtvmr.so:system/vendor/lib/libnvtvmr.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvmmlite_audio.so:system/vendor/lib/libnvmmlite_audio.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvmm_service.so:system/vendor/lib/libnvmm_service.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libardrv_dynamic.so:system/vendor/lib/libardrv_dynamic.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvos.so:system/vendor/lib/libnvos.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvmm_contentpipe.so:system/vendor/lib/libnvmm_contentpipe.so \
    vendor/samsung/i9103/proprietary/vendor/lib/egl/libGLESv1_CM_tegra.so:system/vendor/lib/egl/libGLESv1_CM_tegra.so \
    vendor/samsung/i9103/proprietary/vendor/lib/egl/libGLESv2_tegra.so:system/vendor/lib/egl/libGLESv2_tegra.so \
    vendor/samsung/i9103/proprietary/vendor/lib/egl/libEGL_tegra.so:system/vendor/lib/egl/libEGL_tegra.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvmm_asfparser.so:system/vendor/lib/libnvmm_asfparser.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvomxadaptor.so:system/vendor/lib/libnvomxadaptor.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvmm_manager.so:system/vendor/lib/libnvmm_manager.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvmm_video.so:system/vendor/lib/libnvmm_video.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvmmlite_video.so:system/vendor/lib/libnvmmlite_video.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvmm_image.so:system/vendor/lib/libnvmm_image.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvmmlite_utils.so:system/vendor/lib/libnvmmlite_utils.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvmm_aviparser.so:system/vendor/lib/libnvmm_aviparser.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvomx.so:system/vendor/lib/libnvomx.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libsec-ril.so:system/vendor/lib/libsec-ril.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libnvapputil.so:system/vendor/lib/libnvapputil.so \
    vendor/samsung/i9103/proprietary/vendor/lib/libmpl.so:system/vendor/lib/libmpl.so
